# Generated by Django 6.0.5 on 2026-06-24 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('full_description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/leagues/')),
                ('is_private', models.BooleanField()),
                ('status', models.CharField(default='Чернетка', max_length=20)),
                ('create_at', models.DateField()),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_leagues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'League',
                'verbose_name_plural': 'Leagues',
            },
        ),
        migrations.CreateModel(
            name='ScoringRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_exact_score', models.IntegerField()),
                ('point_correct_winner', models.IntegerField()),
                ('point_correct_diff', models.IntegerField()),
                ('points_home_scored', models.IntegerField()),
                ('points_away_scored', models.IntegerField()),
                ('points_home_clean_sheet', models.IntegerField()),
                ('points_away_clean_sheet', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.league')),
            ],
            options={
                'verbose_name': 'scoring rules',
                'verbose_name_plural': 'scoring rules',
            },
        ),
        migrations.CreateModel(
            name='LeagueMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'ADMIN'), ('moderator', 'MODERATOR'), ('user', 'USER')], default='user', max_length=20)),
                ('total_points', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('league_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='leagues.league')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'League Member',
                'verbose_name_plural': 'League Members',
                'unique_together': {('league_id', 'user_id')},
            },
        ),
    ]
