# Generated by Django 6.0.5 on 2026-06-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaguemember',
            old_name='league_id',
            new_name='league',
        ),
        migrations.RenameField(
            model_name='leaguemember',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='scoringrules',
            old_name='league_id',
            new_name='league',
        ),
    ]
