# Generated by Django 6.0.5 on 2026-07-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_rename_league_id_leaguemember_league_and_more'),
        ('tournaments', '0003_team_alter_match_options_remove_match_away_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='leagues', to='tournaments.team', verbose_name='Команди ліги'),
        ),
    ]
