# Generated by Django 6.0.5 on 2026-07-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_league_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='leagues/'),
        ),
    ]
