# Generated by Django 6.0.5 on 2026-08-05 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_alter_league_logo'),
        ('tournaments', '0004_alter_team_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLeaguePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_correct_winner', models.IntegerField(default=0)),
                ('point_correct_diff', models.IntegerField(default=0)),
                ('point_exact_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='leagues.leaguemember')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_points', to='tournaments.match')),
            ],
            options={
                'verbose_name': 'User League Points',
                'verbose_name_plural': 'User League Points',
                'ordering': ['-created_at'],
                'unique_together': {('league_member', 'match')},
            },
        ),
    ]
