# Generated by Django 6.0.5 on 2026-08-05 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_userleaguepoints'),
        ('results', '0004_remove_prediction_away_clean_sheet_and_more'),
    ]

    operations = [
        # 1. Видалення непотрібних полів зі ScoringRules
        migrations.RemoveField(
            model_name='scoringrules',
            name='points_away_clean_sheet',
        ),
        migrations.RemoveField(
            model_name='scoringrules',
            name='points_away_scored',
        ),
        migrations.RemoveField(
            model_name='scoringrules',
            name='points_home_clean_sheet',
        ),
        migrations.RemoveField(
            model_name='scoringrules',
            name='points_home_scored',
        ),

        # 2. Скинути старий unique_together перед видаленням поля match
        migrations.AlterUniqueTogether(
            name='userleaguepoints',
            unique_together=set(),
        ),

        # 3. Видалити старе поле match
        migrations.RemoveField(
            model_name='userleaguepoints',
            name='match',
        ),

        # 4. Створити нове поле prediction
        migrations.AddField(
            model_name='userleaguepoints',
            name='prediction',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='league_points',
                to='results.prediction'
            ),
            preserve_default=False,
        ),

        # 5. Встановити новий unique_together з уже існуючим полем prediction
        migrations.AlterUniqueTogether(
            name='userleaguepoints',
            unique_together={('league_member', 'prediction')},
        ),

        # 6. Оновити related_name для league_member
        migrations.AlterField(
            model_name='userleaguepoints',
            name='league_member',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='point_entries',
                to='leagues.leaguemember'
            ),
        ),
    ]