# Generated by Django 6.0.5 on 2026-08-06 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_remove_scoringrules_points_away_clean_sheet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringrules',
            name='league',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rules', to='leagues.league'),
        ),
    ]
