# Generated by Django 6.0.5 on 2026-06-24 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0002_rename_league_id_leaguemember_league_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('deadline', models.DateTimeField()),
                ('is_locked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Round',
                'verbose_name_plural': 'Rounds',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=250)),
                ('away_team', models.CharField(max_length=250)),
                ('home_logo', models.ImageField(blank=True, null=True, upload_to='leagues/logos/')),
                ('away_logo', models.ImageField(blank=True, null=True, upload_to='leagues/logos/')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.round')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=250)),
                ('status', models.CharField(default='майбутні', max_length=30)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='leagues.league')),
            ],
            options={
                'verbose_name': 'Tournament',
                'verbose_name_plural': 'Tournaments',
            },
        ),
        migrations.AddField(
            model_name='round',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round', to='tournaments.tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('tournament_id', 'round_number')},
        ),
    ]
