# Generated by Django 6.0.5 on 2026-06-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('tournament', 'round_number')},
        ),
    ]
